#ifndef CALC_PARAMETERS_H
#define CALC_PARAMETERS_H

#define DEBUG_TRACE_GC 0
#define DEBUG_TRACE_EXECUTION 0
#define DEBUG_SHOW_DISASSEMBLY 0

#define INITIAL_GC_THRESHOLD 64

#define STACK_MAX 256
#define SCOPES_MAX 256

#endif //CALC_PARAMETERS_H
