#ifndef CALC_PARAMETERS_H
#define CALC_PARAMETERS_H

#define DEBUG_TRACE_GC 0
#define DEBUG_TRACE_EXECUTION 1
#define DEBUG_SHOW_DISASSEMBLY 1

#define INITIAL_GC_THRESHOLD 64

#define STACK_MAX 256
#define FRAMES_MAX 64
#define SCOPES_MAX 256

#define NATIVE_COUNT 1

#endif //CALC_PARAMETERS_H
